language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database politico_test;' -U postgres
  - psql -c "create user postgres_nevo with password 'bar';" -U postgres

script:
  - pytest --cov=app

after_success:
  - coveralls